apiVersion: v1
kind: Service
metadata:
  name: service-payments
  labels:
    app: payments-service-example
spec:
  selector:
    app: payments-service-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-deployment
  labels:
    app: payments-service-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payments-service-example
  template:
    metadata:
      labels:
        app: payments-service-example
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: 045017788685.dkr.ecr.us-east-1.amazonaws.com/payments-service-example:payments-service-example-dev
        ports:
        - containerPort: 80 