apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service-example-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service-example
      env: dev
  template:
    metadata:
      labels:
        app: payments-service-example
        env: dev
    spec:
      containers:
        - name: contenedor-payments
          image: 045017788685.dkr.ecr.us-east-1.amazonaws.com/payments-service-example:payments-service-example-dev
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ms-payments-service
spec:
  selector:
    app: ms-payments
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080