apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-example-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-service-example
      env: dev
  template:
    metadata:
      labels:
        app: orders-service-example
        env: dev
    spec:
      containers:
        - name: contenedor-orders
          image: 045017788685.dkr.ecr.us-east-1.amazonaws.com/orders-service-example:orders-service-example-dev
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ms-orders-service
spec:
  selector:
    app: ms-orders
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081