name: Deploy to ECR

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      CONTENTFUL_ENVIRONMENT:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      ECR_REPOSITORY:
        required: true
      IMAGE_TAG:
        required: true
      ECR_REGISTRY:
        required: true

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }} #346054926618.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: payments-service-example-dev
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:payments-service-example-dev .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:payments-service-example-dev

    - name: Trigger deploy
      run: |
        aws eks update-kubeconfig --region us-east-1 --name devops-grupo-8-DEV
        kubectl version -o json
        ls
        kubectl apply -f deployment.yml
